// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(craftloop_mobile_ffiFFI)
import craftloop_mobile_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_craftloop_mobile_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_craftloop_mobile_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCraftloopMobileFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * One normalized pointer sample crossing the FFI boundary -- Task 204's
 * mapping target for Jetpack Ink's `MutableStrokeInputBatch`/finished
 * `Stroke` data (position, pressure, tilt, source) and
 * `InputCapabilities`/`PointerButtons`, flattened into plain FFI-safe
 * fields rather than nested records, since UniFFI can cross either
 * shape equally well and a flat record is simpler generated Kotlin/
 * Swift to read.
 */
public struct FfiPointerSample: Equatable, Hashable {
    public var x: Double
    public var y: Double
    public var timestampSeconds: Double
    public var pressure: Double?
    public var tiltXDeg: Double?
    public var tiltYDeg: Double?
    public var source: FfiPointerSource
    public var buttonPrimary: Bool
    public var buttonSecondary: Bool
    public var buttonBarrel: Bool
    /**
     * Real, queried capability flags (Article 4: never fabricated) --
     * see `craftloop_input::InputCapabilities`'s own doc comment. An
     * Android/iPad adapter must set these from an actual platform
     * capability query, never a guess.
     */
    public var capabilityPressure: Bool
    public var capabilityTilt: Bool
    public var capabilityHover: Bool
    public var capabilityPalmRejection: Bool
    public var capabilityEraser: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double, timestampSeconds: Double, pressure: Double?, tiltXDeg: Double?, tiltYDeg: Double?, source: FfiPointerSource, buttonPrimary: Bool, buttonSecondary: Bool, buttonBarrel: Bool, 
        /**
         * Real, queried capability flags (Article 4: never fabricated) --
         * see `craftloop_input::InputCapabilities`'s own doc comment. An
         * Android/iPad adapter must set these from an actual platform
         * capability query, never a guess.
         */capabilityPressure: Bool, capabilityTilt: Bool, capabilityHover: Bool, capabilityPalmRejection: Bool, capabilityEraser: Bool) {
        self.x = x
        self.y = y
        self.timestampSeconds = timestampSeconds
        self.pressure = pressure
        self.tiltXDeg = tiltXDeg
        self.tiltYDeg = tiltYDeg
        self.source = source
        self.buttonPrimary = buttonPrimary
        self.buttonSecondary = buttonSecondary
        self.buttonBarrel = buttonBarrel
        self.capabilityPressure = capabilityPressure
        self.capabilityTilt = capabilityTilt
        self.capabilityHover = capabilityHover
        self.capabilityPalmRejection = capabilityPalmRejection
        self.capabilityEraser = capabilityEraser
    }

    

    
}

#if compiler(>=6)
extension FfiPointerSample: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPointerSample: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPointerSample {
        return
            try FfiPointerSample(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf), 
                timestampSeconds: FfiConverterDouble.read(from: &buf), 
                pressure: FfiConverterOptionDouble.read(from: &buf), 
                tiltXDeg: FfiConverterOptionDouble.read(from: &buf), 
                tiltYDeg: FfiConverterOptionDouble.read(from: &buf), 
                source: FfiConverterTypeFfiPointerSource.read(from: &buf), 
                buttonPrimary: FfiConverterBool.read(from: &buf), 
                buttonSecondary: FfiConverterBool.read(from: &buf), 
                buttonBarrel: FfiConverterBool.read(from: &buf), 
                capabilityPressure: FfiConverterBool.read(from: &buf), 
                capabilityTilt: FfiConverterBool.read(from: &buf), 
                capabilityHover: FfiConverterBool.read(from: &buf), 
                capabilityPalmRejection: FfiConverterBool.read(from: &buf), 
                capabilityEraser: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPointerSample, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
        FfiConverterDouble.write(value.timestampSeconds, into: &buf)
        FfiConverterOptionDouble.write(value.pressure, into: &buf)
        FfiConverterOptionDouble.write(value.tiltXDeg, into: &buf)
        FfiConverterOptionDouble.write(value.tiltYDeg, into: &buf)
        FfiConverterTypeFfiPointerSource.write(value.source, into: &buf)
        FfiConverterBool.write(value.buttonPrimary, into: &buf)
        FfiConverterBool.write(value.buttonSecondary, into: &buf)
        FfiConverterBool.write(value.buttonBarrel, into: &buf)
        FfiConverterBool.write(value.capabilityPressure, into: &buf)
        FfiConverterBool.write(value.capabilityTilt, into: &buf)
        FfiConverterBool.write(value.capabilityHover, into: &buf)
        FfiConverterBool.write(value.capabilityPalmRejection, into: &buf)
        FfiConverterBool.write(value.capabilityEraser, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPointerSample_lift(_ buf: RustBuffer) throws -> FfiPointerSample {
    return try FfiConverterTypeFfiPointerSample.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPointerSample_lower(_ value: FfiPointerSample) -> RustBuffer {
    return FfiConverterTypeFfiPointerSample.lower(value)
}


/**
 * The result of trying to build a real domain stroke from FFI samples
 * -- crossing back out, proving this boundary is a two-way bridge into
 * the real domain core (`craftloop_ink::Stroke::new`'s own validation:
 * non-empty, single consistent `PointerSource`), not merely a
 * type-shape exercise.
 */
public struct FfiStrokeValidation: Equatable, Hashable {
    public var isValid: Bool
    public var sampleCount: UInt32
    public var reason: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(isValid: Bool, sampleCount: UInt32, reason: String?) {
        self.isValid = isValid
        self.sampleCount = sampleCount
        self.reason = reason
    }

    

    
}

#if compiler(>=6)
extension FfiStrokeValidation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStrokeValidation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStrokeValidation {
        return
            try FfiStrokeValidation(
                isValid: FfiConverterBool.read(from: &buf), 
                sampleCount: FfiConverterUInt32.read(from: &buf), 
                reason: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiStrokeValidation, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isValid, into: &buf)
        FfiConverterUInt32.write(value.sampleCount, into: &buf)
        FfiConverterOptionString.write(value.reason, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStrokeValidation_lift(_ buf: RustBuffer) throws -> FfiStrokeValidation {
    return try FfiConverterTypeFfiStrokeValidation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStrokeValidation_lower(_ value: FfiStrokeValidation) -> RustBuffer {
    return FfiConverterTypeFfiStrokeValidation.lower(value)
}


/**
 * Mirrors `craftloop_command::CommandAction` -- the full flat
 * vocabulary across every namespace (Article 237).
 */

public enum FfiCommandAction: Equatable, Hashable {
    
    case pen
    case eraser
    case select
    case sketch
    case orthographic
    case line
    case circle
    case arc
    case rectangle
    case dimension
    case exitSketch
    case addView
    case labelView
    case link
    case resolve





}

#if compiler(>=6)
extension FfiCommandAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCommandAction: FfiConverterRustBuffer {
    typealias SwiftType = FfiCommandAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCommandAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pen
        
        case 2: return .eraser
        
        case 3: return .select
        
        case 4: return .sketch
        
        case 5: return .orthographic
        
        case 6: return .line
        
        case 7: return .circle
        
        case 8: return .arc
        
        case 9: return .rectangle
        
        case 10: return .dimension
        
        case 11: return .exitSketch
        
        case 12: return .addView
        
        case 13: return .labelView
        
        case 14: return .link
        
        case 15: return .resolve
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCommandAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pen:
            writeInt(&buf, Int32(1))
        
        
        case .eraser:
            writeInt(&buf, Int32(2))
        
        
        case .select:
            writeInt(&buf, Int32(3))
        
        
        case .sketch:
            writeInt(&buf, Int32(4))
        
        
        case .orthographic:
            writeInt(&buf, Int32(5))
        
        
        case .line:
            writeInt(&buf, Int32(6))
        
        
        case .circle:
            writeInt(&buf, Int32(7))
        
        
        case .arc:
            writeInt(&buf, Int32(8))
        
        
        case .rectangle:
            writeInt(&buf, Int32(9))
        
        
        case .dimension:
            writeInt(&buf, Int32(10))
        
        
        case .exitSketch:
            writeInt(&buf, Int32(11))
        
        
        case .addView:
            writeInt(&buf, Int32(12))
        
        
        case .labelView:
            writeInt(&buf, Int32(13))
        
        
        case .link:
            writeInt(&buf, Int32(14))
        
        
        case .resolve:
            writeInt(&buf, Int32(15))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCommandAction_lift(_ buf: RustBuffer) throws -> FfiCommandAction {
    return try FfiConverterTypeFfiCommandAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCommandAction_lower(_ value: FfiCommandAction) -> RustBuffer {
    return FfiConverterTypeFfiCommandAction.lower(value)
}



/**
 * Mirrors `craftloop_command::CommandNamespace` (Article 237).
 */

public enum FfiCommandNamespace: Equatable, Hashable {
    
    case notebook
    case sketch
    case orthographic





}

#if compiler(>=6)
extension FfiCommandNamespace: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCommandNamespace: FfiConverterRustBuffer {
    typealias SwiftType = FfiCommandNamespace

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCommandNamespace {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notebook
        
        case 2: return .sketch
        
        case 3: return .orthographic
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiCommandNamespace, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notebook:
            writeInt(&buf, Int32(1))
        
        
        case .sketch:
            writeInt(&buf, Int32(2))
        
        
        case .orthographic:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCommandNamespace_lift(_ buf: RustBuffer) throws -> FfiCommandNamespace {
    return try FfiConverterTypeFfiCommandNamespace.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCommandNamespace_lower(_ value: FfiCommandNamespace) -> RustBuffer {
    return FfiConverterTypeFfiCommandNamespace.lower(value)
}



/**
 * Mirrors `craftloop_command::grammar::GrammarMatch`. `Ambiguous`'s
 * `Vec<&'static str>` becomes owned `Vec<String>` -- a borrowed
 * `'static` slice cannot cross an FFI boundary at all, exactly the kind
 * of domain-shape detail this crate exists to absorb (see the module
 * doc comment) rather than push onto every mobile caller.
 */

public enum FfiGrammarMatch: Equatable, Hashable {
    
    case exact(FfiCommandAction
    )
    case uniquePrefix(FfiCommandAction
    )
    case ambiguous([String]
    )
    case noMatch





}

#if compiler(>=6)
extension FfiGrammarMatch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiGrammarMatch: FfiConverterRustBuffer {
    typealias SwiftType = FfiGrammarMatch

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiGrammarMatch {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .exact(try FfiConverterTypeFfiCommandAction.read(from: &buf)
        )
        
        case 2: return .uniquePrefix(try FfiConverterTypeFfiCommandAction.read(from: &buf)
        )
        
        case 3: return .ambiguous(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 4: return .noMatch
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiGrammarMatch, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .exact(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeFfiCommandAction.write(v1, into: &buf)
            
        
        case let .uniquePrefix(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeFfiCommandAction.write(v1, into: &buf)
            
        
        case let .ambiguous(v1):
            writeInt(&buf, Int32(3))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case .noMatch:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGrammarMatch_lift(_ buf: RustBuffer) throws -> FfiGrammarMatch {
    return try FfiConverterTypeFfiGrammarMatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGrammarMatch_lower(_ value: FfiGrammarMatch) -> RustBuffer {
    return FfiConverterTypeFfiGrammarMatch.lower(value)
}



/**
 * Mirrors `craftloop_input::PointerSource`. Kept as its own FFI enum
 * (Kotlin/Swift get a real sealed enum, not a raw integer) rather than
 * exposing the domain enum directly across the boundary.
 */

public enum FfiPointerSource: Equatable, Hashable {
    
    case simulatedMouse
    case stylus
    case touch





}

#if compiler(>=6)
extension FfiPointerSource: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPointerSource: FfiConverterRustBuffer {
    typealias SwiftType = FfiPointerSource

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPointerSource {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .simulatedMouse
        
        case 2: return .stylus
        
        case 3: return .touch
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPointerSource, into buf: inout [UInt8]) {
        switch value {
        
        
        case .simulatedMouse:
            writeInt(&buf, Int32(1))
        
        
        case .stylus:
            writeInt(&buf, Int32(2))
        
        
        case .touch:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPointerSource_lift(_ buf: RustBuffer) throws -> FfiPointerSource {
    return try FfiConverterTypeFfiPointerSource.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPointerSource_lower(_ value: FfiPointerSource) -> RustBuffer {
    return FfiConverterTypeFfiPointerSource.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPointerSample: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPointerSample]

    public static func write(_ value: [FfiPointerSample], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPointerSample.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPointerSample] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPointerSample]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPointerSample.read(from: &buf))
        }
        return seq
    }
}
/**
 * Resolve `input` against `namespace`'s command grammar (Article 237).
 * Never guesses: an ambiguous prefix comes back as `FfiGrammarMatch::Ambiguous`
 * with every candidate word, exactly like the Rust-only `grammar::resolve`
 * this wraps.
 */
public func resolveCommand(input: String, namespace: FfiCommandNamespace) -> FfiGrammarMatch  {
    return try!  FfiConverterTypeFfiGrammarMatch_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_craftloop_mobile_ffi_fn_func_resolve_command(
        FfiConverterString.lower(input),
        FfiConverterTypeFfiCommandNamespace_lower(namespace),uniffiCallStatus
    )
})
}
public func validateStroke(samples: [FfiPointerSample]) -> FfiStrokeValidation  {
    return try!  FfiConverterTypeFfiStrokeValidation_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_craftloop_mobile_ffi_fn_func_validate_stroke(
        FfiConverterSequenceTypeFfiPointerSample.lower(samples),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_craftloop_mobile_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_craftloop_mobile_ffi_checksum_func_resolve_command() != 38915) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftloop_mobile_ffi_checksum_func_validate_stroke() != 13820) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCraftloopMobileFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all